version: '3.9'
networks:
  blesta:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"

services:
  blesta:
    hostname: blestadev1.hexonet.net
    mac_address: 02:42:AC:10:ED:0B
    container_name: dstack-blesta
    environment:
      MYSQL_ROOT_PASSWORD: middleware
      MYSQL_DATABASE: blestadb
      MYSQL_USER_NAME: admin
      MYSQL_PASSWORD: middleware
      MYSQL_HOST: localhost
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 8.1
    volumes:
      - ..:/usr/share/rtldev-middleware-blesta:cached
    ports:
      - 80:80
      - 3306:3306
    networks:
      blesta:
        ipv4_address: 172.16.238.12

  phpmyadmin:
    image: phpmyadmin
    container_name: dstack-phpmyadmin-blesta
    restart: always
    depends_on:
      - blesta
    environment:
      PMA_HOST: 172.16.238.12
      PMA_PORT: 3306
    ports:
      - 8082:80
    networks:
      - blesta
