name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/blesta-ispapi-release.yml@main
    secrets: inherit